Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['(\A|\s)#']

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/*'
