default: &default
  adapter: <%= ENV.fetch('PETLOVE_DATABASE_ADAPTER') %>
  encoding: <%= ENV.fetch('PETLOVE_DATABASE_ENCODING') %>
  pool: <%= ENV.fetch('PETLOVE_DATABASE_POOL') { 5 } %>
  host: <%= ENV.fetch('PETLOVE_DATABASE_HOST') %>
  username: <%= ENV.fetch('PETLOVE_DATABASE_USER') %>
  password: <%= ENV.fetch('PETLOVE_DATABASE_PASSWORD') %>

development:
  <<: *default
  database: <%= "#{ENV.fetch('PETLOVE_DATABASE')}_development" %>

test:
  <<: *default
  database: <%= "#{ENV.fetch('PETLOVE_DATABASE')}_test" %>

production:
  <<: *default
  database: <%= "#{ENV.fetch('PETLOVE_DATABASE')}_production" %>
  username: <%= ENV.fetch('PETLOVE_PRODUCTION_DATABASE_USER') %>
  password: <%= ENV.fetch('PETLOVE_PRODUCTION_DATABASE_PASSWORD') %>
